services:
  # Backend API Service
  - type: web
    name: preptalk-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  # Frontend Web Service
  - type: web
    name: preptalk-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NEXT_PUBLIC_API_URL
        value: https://preptalk-backend.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false